name: flutter_modular_5
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^3.1.0
  firebase_auth: ^1.1.0
  firebase_core: ^1.0.3
  google_sign_in: ^5.0.2
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  hive: ^2.0.3
  path_provider: ^2.0.1
  shared_preferences: ^2.0.5
  bloc: 7.0.0-nullsafety.3
  flutter_bloc: 7.0.0-nullsafety.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3
  flutter_modular_test: ^1.0.1
  build_runner: ^1.12.2
  bloc_test: 8.0.0-nullsafety.2
flutter:
  uses-material-design: true
